config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: %i[sessions]

  post 'carrinho/adiciona_produto_no_carrinho', to: 'carrinho#adiciona_produto_no_carrinho'
  post 'carrinho/remove_item_do_carrinho', to: 'carrinho#remove_item_do_carrinho'
  get 'carrinho', to: 'carrinho#carrega_carrinho'
  get 'home/index', to: 'home#index'
  root 'home#index'

  resources :produtos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produto.rb
# app/models/produto.rb
class Produto < ApplicationRecord
  include Rails.application.routes.url_helpers

  validates :nome, presence: true
  validates :preco, presence: true, numericality: { greater_than_or_equal_to: 0 }
  # validates :imagem, presence: true
  has_one_attached :imagem
  after_commit :atualizar_url_imagem, on: %i[create update], if: -> { imageUrl.blank? }

  def atualizar_url_imagem
    # Verifica se a imagem foi anexada
    return unless imagem.attached? && imagem.blob.persisted?

      # Atualiza o atributo 'imageUrl' com a URL da imagem anexada
      update(imageUrl: url_for(imagem))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :define_produtos

  private

  def define_produtos
    @produtos = Produto.all
  end
end

app/controllers/carrinho_controller.rb
class CarrinhoController < ApplicationController
  def adiciona_produto_no_carrinho
    flash.now[:notice] = 'YEEEEEY'
    produto = params[:produto]
    if session[:cart].is_a?(Array)
      if session[:cart].include?(produto)
        flash.now[:alert] = 'Este produto já está incluído no carrinho.'
      else
        session[:cart] << produto
        flash.now[:notice] = 'Produto adicionado ao carrinho com sucesso!'
      end
    else
      session[:cart] = [produto]
    end
    respond_to do |format|
      # Substitua :carrinho/carrega_carrinho pelo nome do template que você deseja renderizar
      format.html do
        render 'carrinho/carrega_carrinho'
      end
      format.json { render json: { notice: flash.now[:notice], alert: flash.now[:alert] } }
    end
  end

  def carrega_carrinho
    # flash.now[:notice] = "Oi"
    @cart = session[:cart]
    respond_to do |format|
      format.html
      format.json { render json: @cart }
    end
  end

  def remove_item_do_carrinho
    flash.now[:notice] = 'tchau'
    produto = params[:produto]
    if session[:cart].is_a?(Array) && session[:cart].include?(produto)
      session[:cart].delete(produto)
      flash.now[:notice] = 'Produto removido do carrinho com sucesso!'
    else
      flash.now[:alert] = 'Este produto não está incluído no carrinho.'
      respond_to do |format|
        # Substitua :carrinho/carrega_carrinho pelo nome do template que você deseja renderizar
        format.html do
          render 'carrinho/carrega_carrinho', notice: flash.now[:notice], alert: flash.now[:alert]
        end
        format.json { render json: { alert: flash.now[:alert] } }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @lista = ['Item 1', 'Item 2', 'Item 3', '', '', '', '', '', '', '', '', '', '']
  end
end

app/controllers/produtos_controller.rb
# app/controllers/produtos_controller.rb

class ProdutosController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_produto, only: %i[show edit update destroy]

  def index
    @produtos = Produto.all
  end

  def new
    @produto = Produto.new
  end

  def show
  end

  def create
    @produto = Produto.new(produto_params)
    if @produto.save
      begin
        image_change(@produto)
        flash.now[:notice] = 'Produto criado com sucesso!'
        redirect_to @produto
      rescue StandardError => e
        flash.now[:alert] = "Alguma coisa deu errado: #{e}"
        render :new
      end
    else
      flash.now[:alert] = "Alguma coisa deu errado. #{@produto.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def edit
  end

  def update
    if @produto.update(produto_params)
      begin
        image_change(@produto)
        flash.now[:notice] = 'Produto atualizado com sucesso!'
        redirect_to @produto
      rescue StandardError => e
        flash.now[:alert] = "Alguma coisa deu errado: #{e}"
        render :edit
      end
    else
      flash.now[:alert] = "Alguma coisa deu errado. #{@produto.errors.full_messages.join(', ')}"
      render :edit
    end
  end

  def destroy
    @produto.destroy
    flash.now[:notice] = 'Produto excluído com sucesso!'
    redirect_to produtos_path
  end

  private

  def produto_params
    params.require(:produto).permit(:id, :nome, :descricao, :preco, :imagem, :imageUrl)
  end

  def check_admin
    return if current_user&.admin?

    redirect_to root_path, alert: 'Acesso negado. Você precisa ser um administrador para realizar essa ação.'
  end

  def image_change(produto)
    imagem = params[:produto][:imagem]
    return if imagem.nil?

    produto.imagem.purge if produto.imagem.attached?
    produto.imagem.attach(imagem)
  end

  def set_produto
    @produto = Produto.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin, only: [:admin_action]

  private

  def check_admin
    return if current_user.admin?

      flash[:alert] = 'Você não tem permissão para acessar esta página.'
      redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carrinho/carrega_carrinho.html.erb
<!-- app/views/home/index.html.erb -->
<body data-flash-messages="<%= JSON.dump(flash.to_a) %>">
  <p><%= flash[:notice] %></p> <!-- Exibe a mensagem de flash notice -->
  <p><%= flash[:alert] %></p> <!-- Exibe a mensagem de flash alert -->
</body>

<div id="svelte-app" data-cart="<%= @cart.to_json %>"></div>

<script src="<%= asset_pack_path('cart_svelte.js') %>"></script>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<div id="svelte-app" data-lista="<%= @produtos.to_json %>"></div>

<script src="<%= asset_pack_path('hello_svelte.js') %>"></script>

app/views/layouts/_footer.html.erb
<%= stylesheet_link_tag 'footer', media: 'all' %>

<footer>
  <div class="container">
    <p>Copyright &copy; Criado por: <a href="https://fernando-melo.social" target="_blank">Fernando Melo</a> - <%= Time.now.year %>. <br/>Todos os direitos reservados.</p>
    <div>
      <h3>
        <strong>Contato:</strong>
      </h3>
      <ul class="nav">
        <li>
          <h4>
            <%= link_to "<i class='fab fa-whatsapp fa-lg'></i> (38) 9728-0364".html_safe, "https://api.whatsapp.com/send?phone=#{ENV['NUMERO_REDIRECIONAMENTO']}", target: "_blank" %>
          </h4>
        </li>
        
        <li>
          <h4>
            <%= link_to "<i class='fab fa-instagram fa-lg'></i> Instagram".html_safe, "https://www.instagram.com/mundo_de_princesa_lacos/", target: "_blank" %>
          </h4>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_navbar_bottom.html.erb
<nav>
  <div class="navbar-container">
    <%= link_to root_path do %>
      <%= image_tag("logo.svg", class: "navbar-icon") %>
    <% end %>
    <div class="navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/"><i class="fas fa-home fa-lg"></i></a>
        </li>
        <li class="nav-item">
          <a href="/carrinho"><i class="fas fa-shopping-cart fa-lg"></i></a>
        </li>
      </ul>
    </div>
    <%# <div class="nav-cart">
    </div> %>
  </div>
</nav>

app/views/layouts/_navbar_top.html.erb
<div class="navbar">
  <div class="navbar-left">
    <div class="navbar-phone">
      <a href="https://api.whatsapp.com/send?phone=<%=ENV['NUMERO_REDIRECIONAMENTO']%>" target="_blank">+55 38 9728-0364</span>
    </div>
  </div>
  <div class="navbar-right">
    <% if current_user.present? %>
        <% if current_user.admin? %>
          <a class="nav-link" href="/produtos"> Produtos </a>
        <% end %>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-sign-out"></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
        <i class="fa fa-sign-in"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mundo De Princesa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="shortcut icon" type="image/svg+xml" href="/assets/logo.svg">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Meta dados para SEO -->
    <meta name="description" content="Mundo De Princesa - Loja online de venda de laços">
    <meta name="keywords" content="Mundo De Princesa, laços, venda de laços, site de venda de laços, laços, loja online">
    <meta name="author" content="Fernando Melo">

    <!-- Meta dados para redes sociais -->
    <meta property="og:title" content="Mundo De Princesa - Loja online de venda de laços">
    <meta property="og:description" content="Mundo De Princesa é uma loja online especializada em venda de laços.">
    <meta property="og:image" content="https://mundo-de-princesa-production.up.railway.app/assets/logo.svg">
    <meta property="og:url" content="https://mundo-de-princesa-production.up.railway.app/">
    <meta property="og:type" content="website">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body data-flash-messages="<%= JSON.dump(flash.to_a) %>">
    <%= render 'layouts/navbar_top' %>

    <%= render 'layouts/navbar_bottom' %>
    
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/produtos/_form.html.erb
<!-- app/views/produtos/form.html.erb -->
<%= stylesheet_link_tag 'produtos_form', media: 'all' %>


<h1><%= action_name == 'new' ? 'Novo Produto' : 'Editar Produto' %></h1>

<%= form_with model: @produto, url: action_name == 'new' ? produtos_path : produto_path(@produto), local: true do |form| %>
  <%= form.label :nome, 'Nome' %>
  <%= form.text_field :nome %>

  <%= form.label :descricao, 'Descrição' %>
  <%= form.text_area :descricao %>

  <%= form.label :preco, 'Preço' %>
  <%= form.number_field :preco, step: 0.01 %>

  <%= form.label :imagem, 'Imagem' %>
  <%= form.file_field :imagem %>



  <%= form.submit action_name == 'new' ? 'Criar Produto' : 'Atualizar Produto' %>
<% end %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/edit.html.erb
<!-- app/views/produtos/form.html.erb -->
<%= stylesheet_link_tag 'produtos_form', media: 'all' %>


<h1>'Editar Produto'</h1>

<%= form_with model: @produto, url: produto_path(@produto), local: true do |form| %>
  <%= form.label :nome, 'Nome' %>
  <%= form.text_field :nome %>

  <%= form.label :descricao, 'Descrição' %>
  <%= form.text_area :descricao %>

  <%= form.label :preco, 'Preço' %>
  <%= form.number_field :preco, step: 0.01, value: number_with_precision(@produto.preco, precision: 2) %>

  <%= form.label :imagem, 'Imagem' %>
  <%= form.file_field :imagem %>

  <br/>
  <br/>
  <%= form.submit 'Atualizar Produto' %>
<% end %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<!-- app/views/home/index.html.erb -->
<div id="svelte-app" data-lista="<%= @produtos.to_json %>" data-admin="<%= current_user&.admin? %>"></div>

<script src="<%= asset_pack_path('hello_svelte.js') %>"></script>

app/views/produtos/new.html.erb
<!-- app/views/produtos/form.html.erb -->
<%= stylesheet_link_tag 'produtos_form', media: 'all' %>


<h1>Novo Produto</h1>

<%= form_with model: @produto, url: produtos_path, local: true do |form| %>
  <%= form.label :nome, 'Nome' %>
  <%= form.text_field :nome %>

  <%= form.label :descricao, 'Descrição' %>
  <%= form.text_area :descricao %>

  <%= form.label :preco, 'Preço' %>
  <%= form.number_field :preco, step: 0.01, value: number_with_precision(0, precision: 2) %>

  <%= form.label :imagem, 'Imagem' %>
  <%= form.file_field :imagem %>

  <br/>
  <br/>
  <%= form.submit 'Criar Produto'%>
<% end %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<!-- app/views/home/index.html.erb -->
<div id="svelte-app" data-produto="<%= @produto.to_json %>" data-admin="<%= current_user&.admin? %>"></div>

<script src="<%= asset_pack_path('show_produto.js') %>"></script>